services:
  - type: web
    name: medhub
    runtime: node
    plan: free
    rootDir: MedHub
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
